import { Vendor, Conversation } from './types'

// Mock vendor data
export const mockVendors: Vendor[] = [
  {
    id: '1',
    name: 'Afro Braids & Beauty',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400',
    rating: 4.8,
    reviewCount: 127,
    distance: 1200,
    priceRange: { min: 50, max: 150 },
    category: 'Hair Styling',
    verified: true,
    availableToday: true,
    homeService: true,
    description: 'Specializing in traditional African braiding, weaves, and natural hair care.',
    services: ['Box Braids', 'Cornrows', 'Weaves', 'Natural Hair Styling', 'Hair Treatment'],
    address: '123 Main St, Downtown',
    phone: '(555) 123-4567',
    openHours: 'Mon-Sat: 9AM - 7PM',
  },
  {
    id: '2',
    name: 'Mama Africa Kitchen',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
    rating: 4.9,
    reviewCount: 203,
    distance: 800,
    priceRange: { min: 15, max: 45 },
    category: 'Catering',
    verified: true,
    availableToday: false,
    homeService: true,
    description: 'Authentic African cuisine with delivery. Perfect for events and daily meals.',
    services: ['Event Catering', 'Home Delivery', 'Meal Prep', 'Traditional Dishes'],
    address: '456 Food Court, Market District',
    phone: '(555) 234-5678',
    openHours: 'Every day: 11AM - 9PM',
  },
  {
    id: '3',
    name: 'Ubuntu Tech Repair',
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400',
    rating: 4.7,
    reviewCount: 89,
    distance: 2500,
    priceRange: { min: 30, max: 200 },
    category: 'Tech Services',
    verified: true,
    availableToday: true,
    homeService: false,
    description: 'Professional phone, laptop, and tablet repair services.',
    services: ['Phone Repair', 'Laptop Repair', 'Data Recovery', 'Screen Replacement'],
    address: '789 Tech Ave, Innovation Hub',
    phone: '(555) 345-6789',
    openHours: 'Mon-Fri: 10AM - 6PM',
  },
  {
    id: '4',
    name: 'Diaspora Threads',
    image: 'https://images.unsplash.com/photo-1618453292507-4959ece6429e?w=400',
    rating: 4.6,
    reviewCount: 156,
    distance: 1800,
    priceRange: { min: 25, max: 100 },
    category: 'Fashion',
    verified: false,
    availableToday: true,
    homeService: false,
    description: 'Custom African attire, alterations, and fashion design.',
    services: ['Custom Tailoring', 'Alterations', 'Traditional Wear', 'Modern Fashion'],
    address: '321 Fashion St, Arts Quarter',
    phone: '(555) 456-7890',
    openHours: 'Tue-Sat: 10AM - 6PM',
  },
  {
    id: '5',
    name: 'Heritage Music Academy',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400',
    rating: 4.9,
    reviewCount: 74,
    distance: 3200,
    priceRange: { min: 40, max: 80 },
    category: 'Education',
    verified: true,
    availableToday: false,
    homeService: true,
    description: 'Learn traditional African music and instruments from master teachers.',
    services: ['Drum Lessons', 'Dance Classes', 'Music Theory', 'Private Tutoring'],
    address: '654 Arts Blvd, Culture Center',
    phone: '(555) 567-8901',
    openHours: 'Mon-Sun: 2PM - 8PM',
  },
]

export const mockConversations: Conversation[] = [
  {
    id: '1',
    vendorId: '1',
    vendorName: 'Afro Braids & Beauty',
    vendorImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=100',
    lastMessage: 'Yes, I have availability this Saturday at 2PM',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    unread: 2,
  },
  {
    id: '2',
    vendorId: '2',
    vendorName: 'Mama Africa Kitchen',
    vendorImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=100',
    lastMessage: 'Thank you for your order! It will be ready in 30 minutes.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    unread: 0,
  },
  {
    id: '3',
    vendorId: '3',
    vendorName: 'Ubuntu Tech Repair',
    vendorImage: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=100',
    lastMessage: 'Your phone is ready for pickup',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
    unread: 0,
  },
]

export const categories = [
  'All',
  'Hair Styling',
  'Catering',
  'Tech Services',
  'Fashion',
  'Education',
  'Transportation',
  'Events',
  'Legal',
  'Health',
]
